import 'app_settings.dart';

/// عربي / English UI strings -- single source of truth for both languages.
/// Extracted verbatim from Sarah's main.dart.
class Strings {
  static final Map<String, Map<String, String>> _v = {
    'ar': {
      'app_name': 'أثَر',
      'tagline': 'ازرع عاداتك المالية.. واحصد مزرعتك',
      'create_account': 'إنشاء حساب جديد',
      'login': 'تسجيل الدخول',
      'signup_title': 'إنشاء حساب',
      'signup_welcome': 'مرحباً بك في أثَر 🌴',
      'signup_subtitle': 'أنشئ حسابك للبدء في تتبع أهدافك المالية',
      'first_name': 'الاسم الأول',
      'last_name': 'الاسم الثاني',
      'phone': 'رقم الجوال',
      'email': 'البريد الإلكتروني',
      'password': 'الرقم السري',
      'terms_agree': 'أوافق على الشروط والأحكام وسياسة الخصوصية الخاصة بتطبيق أثَر',
      'data_link_agree': 'أوافق على ربط حسابي البنكي عبر خدمة المصرفية المفتوحة لتحليل صرفي وادخاري وبناء المزرعة',
      'create_account_btn': 'إنشاء الحساب',
      'have_account': 'لديك حساب بالفعل؟ سجل دخولك',
      'login_title': 'تسجيل الدخول',
      'welcome_back': 'أهلاً بعودتك 👋',
      'login_subtitle': 'سجّل دخولك لمتابعة رحلتك المالية',
      'forgot_password': 'نسيت كلمة المرور؟',
      'login_btn': 'دخول',
      'no_account': 'ليس لديك حساب؟ سجل الآن',
      'quick_login': 'دخول سريع',
      'quick_login_title': 'الدخول السريع',
      'quick_login_subtitle': 'أدخل رمز الدخول السريع المكوّن من 5 أرقام',
      'create_quick_login_title': 'إنشاء رمز الدخول السريع',
      'create_code_subtitle': 'اختر رمزاً مكوّناً من 5 أرقام لتسجيل الدخول بسرعة لاحقاً',
      'confirm_code_subtitle': 'أعد إدخال الرمز للتأكيد',
      'codes_dont_match': 'الرمزان غير متطابقين، حاول مرة أخرى',
      'quick_login_created': 'تم إنشاء رمز الدخول السريع بنجاح',
      'nav_farm': 'المزرعة',
      'nav_dashboard': 'لوحة البيانات',
      'nav_profile': 'حسابي',
      'farm_title': 'مزرعة أثَر',
      'farm_growing': 'مزرعتك في طريقها للنمو 🌱',
      'farm_desc': 'سيتم تصميم المزرعة الرقمية هنا لاحقاً، وستنمو تلقائياً كلما اقتربت من تحقيق أهدافك في الادخار',
      'dashboard_title': 'لوحة البيانات',
      'total_balance': 'الرصيد الإجمالي',
      'balance_note': 'يتم تحديثه تلقائياً عبر البنكية المفتوحة',
      'monthly_spending': 'الصرف الشهري',
      'monthly_saving': 'الادخار الشهري',
      'goal_progress': 'تقدمك نحو الهدف',
      'no_bank_linked': 'لم يتم ربط الحساب البنكي بعد',
      'spending_categories': 'أقسام الصرف',
      'cat_restaurants': 'مطاعم وكافيهات',
      'cat_shopping': 'تسوق',
      'cat_transport': 'مواصلات',
      'cat_bills': 'فواتير',
      'cat_other': 'أخرى',
      'profile_title': 'البيانات الشخصية',
      'account_section': 'الحساب',
      'app_section': 'التطبيق',
      'name': 'الاسم',
      'goals': 'أهدافي المالية',
      'notifications': 'الإشعارات',
      'settings': 'الإعدادات',
      'logout': 'تسجيل الخروج',
      'edit_personal_data': 'تعديل بياناتي الشخصية',
      'settings_personal_section': 'البيانات الشخصية',
      'appearance': 'المظهر',
      'dark_mode': 'الوضع الليلي',
      'language': 'اللغة',
      'arabic': 'العربية',
      'english': 'English',
      'text_size': 'حجم الخط',
      'size_small': 'صغير',
      'size_medium': 'متوسط',
      'size_large': 'كبير',
      'size_xlarge': 'كبير جداً',
      'security_section': 'الأمان',
      'create_quick_code_tile': 'إنشاء رمز الدخول السريع',
      'other_settings': 'إعدادات أخرى',
      'about_app': 'عن التطبيق',
      'delete_account': 'حذف الحساب',
      'save_changes': 'حفظ التعديلات',
      'saved_success': 'تم حفظ التعديلات بنجاح',
    },
    'en': {
      'app_name': 'Athar',
      'tagline': 'Grow your financial habits.. harvest your farm',
      'create_account': 'Create New Account',
      'login': 'Log In',
      'signup_title': 'Create Account',
      'signup_welcome': 'Welcome to Athar 🌴',
      'signup_subtitle': 'Create your account to start tracking your financial goals',
      'first_name': 'First Name',
      'last_name': 'Last Name',
      'phone': 'Phone Number',
      'email': 'Email',
      'password': 'Password',
      'terms_agree': "I agree to Athar's Terms & Conditions and Privacy Policy",
      'data_link_agree': 'I agree to link my bank account via Open Banking to analyze my spending and saving, and build my farm',
      'create_account_btn': 'Create Account',
      'have_account': 'Already have an account? Log in',
      'login_title': 'Log In',
      'welcome_back': 'Welcome back 👋',
      'login_subtitle': 'Log in to continue your financial journey',
      'forgot_password': 'Forgot password?',
      'login_btn': 'Log In',
      'no_account': "Don't have an account? Sign up",
      'quick_login': 'Quick Login',
      'quick_login_title': 'Quick Login',
      'quick_login_subtitle': 'Enter your 5-digit quick login code',
      'create_quick_login_title': 'Create Quick Login Code',
      'create_code_subtitle': 'Choose a 5-digit code to log in quickly next time',
      'confirm_code_subtitle': 'Re-enter the code to confirm',
      'codes_dont_match': "The codes don't match, try again",
      'quick_login_created': 'Quick login code created successfully',
      'nav_farm': 'Farm',
      'nav_dashboard': 'Dashboard',
      'nav_profile': 'Profile',
      'farm_title': 'Athar Farm',
      'farm_growing': 'Your farm is on its way to growing 🌱',
      'farm_desc': 'The digital farm will be designed here later, and will grow automatically as you get closer to your savings goals',
      'dashboard_title': 'Dashboard',
      'total_balance': 'Total Balance',
      'balance_note': 'Automatically updated via Open Banking',
      'monthly_spending': 'Monthly Spending',
      'monthly_saving': 'Monthly Saving',
      'goal_progress': 'Your Goal Progress',
      'no_bank_linked': 'No bank account linked yet',
      'spending_categories': 'Spending Categories',
      'cat_restaurants': 'Restaurants & Cafes',
      'cat_shopping': 'Shopping',
      'cat_transport': 'Transportation',
      'cat_bills': 'Bills',
      'cat_other': 'Other',
      'profile_title': 'Personal Info',
      'account_section': 'Account',
      'app_section': 'App',
      'name': 'Name',
      'goals': 'My Financial Goals',
      'notifications': 'Notifications',
      'settings': 'Settings',
      'logout': 'Log Out',
      'edit_personal_data': 'Edit My Personal Data',
      'settings_personal_section': 'Personal Data',
      'appearance': 'Appearance',
      'dark_mode': 'Dark Mode',
      'language': 'Language',
      'arabic': 'Arabic',
      'english': 'English',
      'text_size': 'Text Size',
      'size_small': 'Small',
      'size_medium': 'Medium',
      'size_large': 'Large',
      'size_xlarge': 'Extra Large',
      'security_section': 'Security',
      'create_quick_code_tile': 'Create Quick Login Code',
      'other_settings': 'Other Settings',
      'about_app': 'About the App',
      'delete_account': 'Delete Account',
      'save_changes': 'Save Changes',
      'saved_success': 'Changes saved successfully',
    },
  };

  static String t(String key) {
    return _v[appSettings.locale.languageCode]?[key] ?? _v['ar']![key] ?? key;
  }
}

String tr(String key) => Strings.t(key);
